=== valentinedwv/incf-dai/atlas-aba/trunk/src/main/resources/WaxMlSchema/WaxML_Base.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio Developer Edition (Education) 8.1.2.2399 (http://www.liquid-technologies.com)-->
<xs:schema xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wax="http://www.incf.org/waxML" xmlns:xlink="http://www.w3.org/1999/xlink" elementFormDefault="qualified" targetNamespace="http://www.incf.org/waxML" version="0.8" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd" namespace="http://www.opengis.net/gml/3.2" />
    <xs:import schemaLocation="http://schemas.opengis.net/xlink/1.0.0/xlinks.xsd" namespace="http://www.w3.org/1999/xlink" />
    <xs:complexType name="BaseResponseType">
        <xs:sequence>
            <xs:element name="queryInfo" type="QueryInfoType" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="QueryInfoType">
        <xs:sequence>
            <xs:element name="timeCreated" type="xs:dateTime" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation> Time that this process was run, and this document was created</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="queryUrl" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>                      The URL that was used to make this document.
Optional</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:anyURI">
                            <xs:attribute name="name" type="xs:Name" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="criteria" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="input" minOccurs="0" maxOccurs="unbounded">
                            <xs:annotation>
                                <xs:documentation>Name of the input parameter, and it's value. This can be any element, eg a gml point</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="xs:anyType">
                                        <xs:attribute name="name" type="xs:Name" />
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="POI" type="POIType" />
    <xs:complexType name="POIType">
        <xs:choice>
            <xs:element ref="gml:Point" />
        </xs:choice>
    </xs:complexType>
    <xs:element name="boundedBy" type="gml:BoundingShapeType" />
    <xs:complexType name="CoordinateTransformationInfoType">
        <xs:sequence>
            <xs:element name="coordinateTransformation" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="order" type="xs:int" use="required" />
                    <xs:attribute name="code" type="xs:string" use="required" />
                    <xs:attribute name="hub" type="xs:Name" use="required" />
                    <xs:attribute name="inputSrsCode" type="xs:QName" use="required" />
                    <xs:attribute name="targetSrsCode" type="xs:QName" use="required" />
                    <xs:attribute name="accuracy" type="xs:float" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="coordinateTransformationInfoResponse" type="CoordinateTransformationInfoResponseType" />
    <xs:complexType name="CoordinateTransformationInfoResponseType">
        <xs:complexContent>
            <xs:extension base="BaseResponseType">
                <xs:sequence>
                    <xs:element name="coordinateTransformationInfo" type="CoordinateTransformationInfoType" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="structureTermsResponse" type="StructureTermsResponseType" />
    <xs:complexType name="StructureTermsResponseType">
        <xs:complexContent>
            <xs:extension base="BaseResponseType">
                <xs:sequence>
                    <xs:element name="structureTerms" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element xmlns:q1="http://www.incf.org/waxML" name="StructureTerm" type="q1:StructureTermType" minOccurs="0" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="StructureTermType">
        <xs:sequence>
            <xs:element name="structureCode" type="incfCodeType" />
            <xs:element xmlns:q2="http://www.incf.org/waxML" ref="wax:name" minOccurs="0" maxOccurs="1" />
            <xs:element ref="description" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="feature" type="FeatureReferenceType" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FeatureReferenceType">
        <xs:sequence>
            <xs:element name="centroid" type="gml:PointType" minOccurs="0" maxOccurs="1" />
            <xs:element ref="boundedBy" />
            <xs:element xmlns:q1="http://www.isotc211.org/2005/gmd" name="Url">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:anyURI">
                            <xs:attribute name="srsName" type="xs:token" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="format" type="geometryFomatCodeList" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="incfCodeType">
        <xs:complexContent>
            <xs:extension base="gml:CodeWithAuthorityType">
                <xs:attribute name="isDefault" type="xs:boolean" />
                <xs:attribute ref="gml:id" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="geometryFomatCodeList">
        <xs:union memberTypes="geomFormatEnum string" />
    </xs:simpleType>
    <xs:simpleType name="geomFormatEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="shape" />
            <xs:enumeration value="SimpleFeaturesText" />
            <xs:enumeration value="gml-sf" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="transformationResponse" type="TransformationResponseType" />
    <xs:complexType name="TransformationResponseType">
        <xs:complexContent>
            <xs:extension base="BaseResponseType">
                <xs:sequence>
                    <xs:element ref="POI" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ImagesResponseType">
        <xs:complexContent>
            <xs:extension base="BaseResponseType">
                <xs:sequence>
                    <xs:element name="Image2Dcollection" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="image2dType" type="Image2DType" minOccurs="0" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="Image2DType">
        <xs:sequence>
            <xs:element name="imageSource" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:anyURI">
                            <xs:attribute name="thumbnanil" type="xs:anyURI" />
                            <xs:attribute name="metadata" type="xs:anyURI" />
                            <xs:attribute name="name" type="xs:normalizedString" />
                            <xs:attribute name="srsName" type="xs:token" />
                            <xs:attribute name="format" type="xs:token" />
                            <xs:attribute name="relavance" type="xs:float" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="imagePosition">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="imagePlaneEquation" type="incfSrsType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="imagePlanePlacement " type="incfSrsType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="corner" minOccurs="0" maxOccurs="4">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element ref="gml:Point" />
                                </xs:sequence>
                                <xs:attribute name="position" type="PositionEnum" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="incfSrsType">
        <xs:simpleContent>
            <xs:extension base="gml:NameList">
                <xs:attribute name="srsName" type="xs:token" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="PositionEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="topleft" />
            <xs:enumeration value="bottomleft" />
            <xs:enumeration value="topright" />
            <xs:enumeration value="bottomright" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="genesResponse" type="GenesResponseType" />
    <xs:complexType name="GenesResponseType">
        <xs:complexContent>
            <xs:extension base="BaseResponseType">
                <xs:all>
                    <xs:element name="genesByPOI" type="GeneByPoiType" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="GeneByPoiType">
        <xs:sequence>
            <xs:element name="gene" type="GeneType" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="expressionLevel" type="GeneExpressionLevelType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GeneType">
        <xs:sequence>
            <xs:element name="symbol" type="GeneSymbolType" />
            <xs:element xmlns:q3="http://www.incf.org/waxML/" ref="wax:name" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="mgiMarkerAccesionId" type="xs:QName" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="organism" type="incfCodeType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>The name of the organism. Use the codespace attribute for any external reference.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GeneExpressionLevelType">
        <xs:annotation>
            <xs:documentation>This is an xlink to another GeneSymbolType element. Eg to link to a gene/symbol[@gml:id=ABc123], a geneExpressionLevel  with this attribute would include this attribute 
@xlink:href='ABc123'
</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="geneSymbol" type="GeneSymbolType">
                <xs:annotation>
                    <xs:documentation>Contains the code for the geneSymbol. This symbol MUST be found in the gene elements in the genesByPOI list.

The codeSpace attribute can optionally be used to add information to indentify the source.
xlink can be used to link a gene. Eg to link to a gene/symbol[@gml:id=ABc123], a geneExpressionLevel  with this attribute would include this attribute 
@xlink:href='ABc123'
</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="level" type="incfCodeType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>contain whatever the resource has - a number or natural language description such as `strong'. The codeSpace attribute can optionally be used to add information to indentify the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="stage" type="incfCodeType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Contains "NEED REFERNCE"
The codeSpace attribute can optionally be used to add information to indentify the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="resourceUri" type="IncfResourceType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Contains an URL to a relevant page at the resource</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GeneSymbolType">
        <xs:complexContent>
            <xs:extension base="incfCodeType">
                <xs:attribute ref="xlink:href">
                    <xs:annotation>
                        <xs:documentation>This is an xlink to another GeneSymbolType element. Eg to link to a gene/symbol[@gml:id=ABc123], a geneExpressionLevel  with this attribute would include this attribute 
@xlink:href='ABc123'
</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="IncfResourceType">
        <xs:simpleContent>
            <xs:extension base="xs:anyURI" />
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="IncfNameType">
        <xs:simpleContent>
            <xs:extension base="xs:Name" />
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="name" type="xs:Name" />
    <xs:element name="description" type="gml:StringOrRefType" />
</xs:schema>

=== valentinedwv/incf-dai/atlas-aba/trunk/src/main/resources/WaxMlSchema/SampleDocuments/GeneResponse.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio Developer Edition (Education) 8.1.2.2399 (http://www.liquid-technologies.com) -->
<genesResponse xmlns="http://www.incf.org/waxML/" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\dev_incf\WaxMlSchema\WaxML_Base.xsd">
    <queryinfo>
        <queryURL name="GetGenesByPOI">URL</queryURL>
        <criteria>
            <input name="POI">
                <gml:Point srsName="INCF:WHS">
                    <gml:pos>x,y,z</gml:pos>
                </gml:Point>
            </input>
            <input name="srsCode">EMAP23</input>
            <input name="filter"></input>
        </criteria>
    </queryinfo> 
    <!-- Genes by POI, or just Genes? -->
    <genesByPOI>
        <gene>
            <symbol gml:id="AAAAB" >Bmp4</symbol>
            <gml:name>bone morphogenetic protein 4</gml:name>
            <mgiMarkerAccesionId>string</mgiMarkerAccesionId>
            <organism>mouse</organism>
        </gene>
        <gene>
            <symbol gml:id="AAAAD" codeSpace="http://www.incf.org/HUBS/ABA">Sox1</symbol>
            <gml:name>SRY-box containing gene 1</gml:name>
            <mgiMarkerAccesionId>MGI:98357</mgiMarkerAccesionId>
            <organism isDefault="1" codeSpace="http://www.incf.org/organisms">mouse</organism>
        </gene>
        <expressionLevel>
            <geneSymbol xlink:href="#AAAAB" />
            <level >strong</level>
            <stage >TS11</stage>
            <resourceUri>http://www.emouseatlas.org/emagewebapp/pages/emage_entry_page.jsf?id=EMAGE:86</resourceUri>
        </expressionLevel>
        <expressionLevel>
            <geneSymbol >Bmp4</geneSymbol>
            <level>detected</level>
            <stage>10.5dpc</stage>
            <resourceUri>http://www.emouseatlas.org/emagewebapp/pages/emage_entry_page.jsf?id=EMAGE:131</resourceUri>
        </expressionLevel>
        <expressionLevel>
            <geneSymbol xlink:href="#AAAAD"/>
            <level>not detected</level>
            <stage>E10.5</stage>
            <resourceUri>http://www.emouseatlas.org/emagewebapp/pages/emage_entry_page.jsf?id=EMAGE:3066</resourceUri>
        </expressionLevel>
    </genesByPOI>
</genesResponse>
