=== valentinedwv/incf-dai/waxml/trunk/AtlasXmlBeans/src/main/xsd/WaxMlSchema/WaxML_Base.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio Developer Edition (Education) 8.1.4.2482 (http://www.liquid-technologies.com)-->
<xs:schema xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wax="http://www.incf.org/WaxML/" xmlns:xlink="http://www.w3.org/1999/xlink" elementFormDefault="qualified" targetNamespace="http://www.incf.org/WaxML/" version="0.8" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd" namespace="http://www.opengis.net/gml/3.2" />
    <xs:import schemaLocation="http://schemas.opengis.net/xlink/1.0.0/xlinks.xsd" namespace="http://www.w3.org/1999/xlink" />
    <xs:complexType name="BaseResponseType">
        <xs:sequence>
            <xs:element name="queryInfo" type="wax:QueryInfoType" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="QueryInfoType">
        <xs:sequence>
            <xs:element name="timeCreated" type="xs:dateTime" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation> Time that this process was run, and this document was created</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="queryUrl" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>                      The URL that was used to make this document.
Optional</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:anyURI">
                            <xs:attribute name="name" type="xs:Name" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="criteria" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="input" minOccurs="0" maxOccurs="unbounded">
                            <xs:annotation>
                                <xs:documentation>Name of the input parameter, and it's value. This can be any element, eg a gml point</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="xs:anyType">
                                        <xs:attribute name="name" type="xs:Name" />
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="POI" type="wax:POIType" />
    <xs:complexType name="POIType">
        <xs:choice>
            <xs:element ref="gml:Point" />
        </xs:choice>
    </xs:complexType>
    <xs:element name="boundedBy" type="gml:BoundingShapeType" />
    <xs:complexType name="CoordinateTransformationInfoType">
        <xs:sequence>
            <xs:element name="coordinateTransformation" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="order" type="xs:int" use="required" />
                    <xs:attribute name="code" type="xs:string" use="required" />
                    <xs:attribute name="hub" type="xs:Name" use="required" />
                    <xs:attribute name="inputSrsCode" type="xs:QName" use="required" />
                    <xs:attribute name="targetSrsCode" type="xs:QName" use="required" />
                    <xs:attribute name="accuracy" type="xs:float" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="coordinateTransformationInfoResponse" type="wax:CoordinateTransformationInfoResponseType" />
    <xs:complexType name="CoordinateTransformationInfoResponseType">
        <xs:complexContent>
            <xs:extension base="wax:BaseResponseType">
                <xs:sequence>
                    <xs:element name="coordinateTransformationInfo" type="wax:CoordinateTransformationInfoType" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="structureTermsResponse" type="wax:StructureTermsResponseType" />
    <xs:complexType name="StructureTermsResponseType">
        <xs:complexContent>
            <xs:extension base="wax:BaseResponseType">
                <xs:sequence>
                    <xs:element name="structureTerms" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="StructureTerm" type="wax:StructureTermType" minOccurs="0" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="StructureTermType">
        <xs:sequence>
            <xs:element name="structureCode" type="wax:incfCodeType" />
            <xs:element ref="wax:name" minOccurs="0" maxOccurs="1" />
            <xs:element ref="wax:description" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="feature" type="wax:FeatureReferenceType" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FeatureReferenceType">
        <xs:sequence>
            <xs:element name="centroid" type="gml:PointType" />
            <xs:element ref="wax:boundedBy" />
            <xs:element xmlns:q1="http://www.isotc211.org/2005/gmd" name="Url">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:anyURI">
                            <xs:attribute name="srsName" type="xs:token" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="format" type="wax:geometryFomatCodeList" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="incfCodeType">
        <xs:complexContent>
            <xs:extension base="gml:CodeWithAuthorityType">
                <xs:attribute name="isDefault" type="xs:boolean" />
                <xs:attribute ref="gml:id" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="geometryFomatCodeList">
        <xs:union memberTypes="wax:geomFormatEnum xs:string" />
    </xs:simpleType>
    <xs:simpleType name="geomFormatEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="shape" />
            <xs:enumeration value="SimpleFeaturesText" />
            <xs:enumeration value="gml-sf" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="transformationResponse" type="wax:TransformationResponseType" />
    <xs:complexType name="TransformationResponseType">
        <xs:complexContent>
            <xs:extension base="wax:BaseResponseType">
                <xs:sequence>
                    <xs:element ref="wax:POI" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ImagesResponseType">
        <xs:complexContent>
            <xs:extension base="wax:BaseResponseType">
                <xs:sequence>
                    <xs:element name="Image2Dcollection" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="image2dType" type="wax:Image2DType" minOccurs="0" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="imagesResponse" type="wax:ImagesResponseType" />
    <xs:complexType name="Image2DType">
        <xs:sequence>
            <xs:element name="imageSource" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:anyURI">
                            <xs:attribute name="thumbnanil" type="xs:anyURI" />
                            <xs:attribute name="metadata" type="xs:anyURI" />
                            <xs:attribute name="name" type="xs:normalizedString" />
                            <xs:attribute name="srsName" type="xs:token" />
                            <xs:attribute name="format" type="wax:IncfRemoteFormats" use="required" />
                            <xs:attribute name="relavance" type="xs:float" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="imagePosition">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="imagePlaneEquation" type="wax:incfSrsType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="imagePlanePlacement " type="wax:incfSrsType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="corner" minOccurs="0" maxOccurs="4">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element ref="gml:Point" />
                                </xs:sequence>
                                <xs:attribute name="position" type="wax:PositionEnum" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="incfSrsType">
        <xs:simpleContent>
            <xs:extension base="gml:NameList">
                <xs:attribute name="srsName" type="xs:token" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="PositionEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="topleft" />
            <xs:enumeration value="bottomleft" />
            <xs:enumeration value="topright" />
            <xs:enumeration value="bottomright" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="genesResponse" type="wax:GenesResponseType" />
    <xs:complexType name="GenesResponseType">
        <xs:complexContent>
            <xs:extension base="wax:BaseResponseType">
                <xs:sequence>
                    <xs:element name="genesByPOI" type="wax:GeneByPoiType" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="GeneByPoiType">
        <xs:sequence>
            <xs:element name="gene" type="wax:GeneType" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="expressionLevel" type="wax:GeneExpressionLevelType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GeneType">
        <xs:sequence>
            <xs:element name="symbol" type="wax:GeneSymbolType" />
            <xs:element ref="wax:name" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="mgiMarkerAccesionId" type="xs:QName" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="organism" type="wax:incfCodeType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>The name of the organism. Use the codespace attribute for any external reference.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GeneExpressionLevelType">
        <xs:annotation>
            <xs:documentation>This is an xlink to another GeneSymbolType element. Eg to link to a gene/symbol[@gml:id=ABc123], a geneExpressionLevel  with this attribute would include this attribute 
@xlink:href='ABc123'
</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="geneSymbol" type="wax:GeneSymbolType">
                <xs:annotation>
                    <xs:documentation>Contains the code for the geneSymbol. This symbol MUST be found in the gene elements in the genesByPOI list.

The codeSpace attribute can optionally be used to add information to indentify the source.
xlink can be used to link a gene. Eg to link to a gene/symbol[@gml:id=ABc123], a geneExpressionLevel  with this attribute would include this attribute 
@xlink:href='ABc123'
</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="level" type="wax:incfCodeType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>contain whatever the resource has - a number or natural language description such as `strong'. The codeSpace attribute can optionally be used to add information to indentify the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="stage" type="wax:incfCodeType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Contains "NEED REFERNCE"
The codeSpace attribute can optionally be used to add information to indentify the source.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="resourceUri" type="wax:IncfResourceType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Contains an URL to a relevant page at the resource</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GeneSymbolType">
        <xs:complexContent>
            <xs:extension base="wax:incfCodeType">
                <xs:attribute ref="xlink:href">
                    <xs:annotation>
                        <xs:documentation>This is an xlink to another GeneSymbolType element. Eg to link to a gene/symbol[@gml:id=ABc123], a geneExpressionLevel  with this attribute would include this attribute 
@xlink:href='ABc123'
</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="IncfResourceType">
        <xs:simpleContent>
            <xs:extension base="xs:anyURI" />
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="IncfNameType">
        <xs:simpleContent>
            <xs:extension base="xs:Name" />
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="name" type="xs:Name" />
    <xs:element name="description" type="gml:StringOrRefType" />
    <xs:simpleType name="IncfRemoteFormatEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="WMS/jpg" />
            <xs:enumeration value="WMS/gif" />
            <xs:enumeration value="WMS/png" />
            <xs:enumeration value="zoomify" />
            <xs:enumeration value="image/jpeg" />
            <xs:enumeration value="image/png" />
            <xs:enumeration value="image/gif" />
            <xs:enumeration value="text/html" />
            <xs:enumeration value="url" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="IncfRemoteFormats">
        <xs:union memberTypes="wax:IncfRemoteFormatEnum xs:string" />
    </xs:simpleType>
    <xs:complexType name="IncfUri">
        <xs:simpleContent>
            <xs:extension base="xs:anyURI">
                <xs:attribute ref="xlink:title" />
                <xs:attribute name="format" type="wax:IncfRemoteFormats" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ImageUrlListType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="url" type="wax:IncfUri" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="CorrelatioMapType">
        <xs:complexContent>
            <xs:extension base="wax:BaseResponseType">
                <xs:choice>
                    <xs:element name="imagesReferenceCollection" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:choice>
                                <xs:element name="imageReferences" type="wax:ImageUrlListType" />
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="correlationMapResponse" type="wax:CorrelatioMapType" />
</xs:schema>

=== valentinedwv/incf-dai/waxml/trunk/AtlasXmlBeans/src/main/xsd/WaxMlSchema/SampleDocuments/StructureTermsResponse_v2.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio Developer Edition (Education) 8.1.2.2399 (http://www.liquid-technologies.com) -->
<wax:structureTermsResponse xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wax="http://www.incf.org/waxML" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.incf.org/waxML C:\dev_incf_google\atlas-aba\trunk\src\main\resources\WaxMlSchema\WaxML_Base.xsd">
      <wax:queryInfo>
        <wax:timeCreated>1998-09-19T09:55:47.49</wax:timeCreated>
        <wax:queryUrl>http://www.liquid-technologies.com</wax:queryUrl>
        <wax:criteria>
            <wax:input name="POI">
                <gml:Point srsName="INCF:ABAvoxel">
                    <gml:pos>x,y,z</gml:pos>
                </gml:Point>
            </wax:input>
            <wax:input name="StructureVocabulary">ABAvoxel</wax:input>
            <wax:input name="StructureFilter">structureset:Fine</wax:input>
        </wax:criteria>
    </wax:queryInfo>
    <wax:structureTerms>
        <wax:StructureTerm>
            <wax:structureCode gml:id="1369" codeSpace="ABAvoxel">HIP</wax:structureCode>
            <wax:name>Hippocampus</wax:name>
            <wax:description>Hippocampus, segmented </wax:description>
            <wax:description xlink:href="http://www.liquid-technologies.com" xlink:arcrole="http://www.liquid-technologies.com" xlink:title="string" xlink:show="embed" xlink:actuate="onRequest" gml:remoteSchema="http://www.liquid-technologies.com">string</wax:description>
            <wax:feature>
                <wax:centroid  gml:id="AAAAB">
                     <gml:Point>
                       <gml:pos axisLabels="X Y Z">5973.4749058039 9195.4749058039</gml:pos>
                    </gml:Point>
                </wax:centroid>
                <wax:boundedBy>
                    <gml:Envelope >
                        <gml:lowerCorner >4086.3349058039</gml:lowerCorner>
                        <gml:upperCorner srsName="http://www.liquid-technologies.com" srsDimension="3193935249">679.2549058039 4681.6949058039</gml:upperCorner>
                    </gml:Envelope>
                </wax:boundedBy>
                <wax:Url srsName="INCF:ABAvoxel">http://www.liquid-technologies.com</wax:Url>
                <wax:format>gml-sf</wax:format>
            </wax:feature>
        </wax:StructureTerm>
        <wax:StructureTerm>
            <wax:structureCode isDefault="0" gml:id="AAAAC" codeSpace="http://www.liquid-technologies.com">string</wax:structureCode>
            <wax:description xlink:show="other" xlink:actuate="onLoad">string</wax:description>
            <wax:description xlink:href="http://www.liquid-technologies.com" xlink:role="http://www.liquid-technologies.com" xlink:arcrole="http://www.liquid-technologies.com" xlink:show="none" gml:remoteSchema="http://www.liquid-technologies.com">string</wax:description>
            <wax:description xlink:href="http://www.liquid-technologies.com" xlink:role="http://www.liquid-technologies.com" xlink:arcrole="http://www.liquid-technologies.com" xlink:title="string" xlink:show="new" xlink:actuate="onRequest" nilReason="http://www.liquid-technologies.com" gml:remoteSchema="http://www.liquid-technologies.com">string</wax:description>
            <wax:description type="simple" xlink:actuate="onRequest" gml:remoteSchema="http://www.liquid-technologies.com">string</wax:description>
            <wax:description type="simple" xlink:role="http://www.liquid-technologies.com" xlink:arcrole="http://www.liquid-technologies.com" xlink:show="replace" xlink:actuate="onLoad" nilReason="http://www.liquid-technologies.com" gml:remoteSchema="http://www.liquid-technologies.com">string</wax:description>
        </wax:StructureTerm>
        <wax:StructureTerm>
            <wax:structureCode isDefault="false" gml:id="AAAAD" codeSpace="http://www.liquid-technologies.com">string</wax:structureCode>
            <wax:name>string</wax:name>
            <wax:description xlink:href="http://www.liquid-technologies.com" xlink:role="http://www.liquid-technologies.com" xlink:arcrole="http://www.liquid-technologies.com" xlink:show="other" nilReason="http://www.liquid-technologies.com" gml:remoteSchema="http://www.liquid-technologies.com">string</wax:description>
            <wax:description type="simple" xlink:actuate="none" nilReason="http://www.liquid-technologies.com">string</wax:description>
            <wax:description xlink:href="http://www.liquid-technologies.com" xlink:actuate="other" nilReason="" gml:remoteSchema="http://www.liquid-technologies.com">string</wax:description>
            <wax:description xlink:href="http://www.liquid-technologies.com" xlink:role="http://www.liquid-technologies.com" xlink:arcrole="http://www.liquid-technologies.com" xlink:title="string" xlink:show="replace">string</wax:description>
            <wax:description xlink:title="string" xlink:show="replace" xlink:actuate="onRequest">string</wax:description>
        </wax:StructureTerm>
        <wax:StructureTerm>
            <wax:structureCode isDefault="1" gml:id="AAAAE" codeSpace="http://www.liquid-technologies.com">string</wax:structureCode>
            <wax:description xlink:href="http://www.liquid-technologies.com" xlink:arcrole="http://www.liquid-technologies.com" gml:remoteSchema="http://www.liquid-technologies.com">string</wax:description>
            <wax:description xlink:href="http://www.liquid-technologies.com" xlink:role="http://www.liquid-technologies.com" xlink:title="string" xlink:show="new" xlink:actuate="onLoad">string</wax:description>
            <wax:description type="simple" xlink:title="string" nilReason="">string</wax:description>
            <wax:description type="simple" nilReason="http://www.liquid-technologies.com">string</wax:description>
        </wax:StructureTerm>
    </wax:structureTerms>
</wax:structureTermsResponse>

=== valentinedwv/incf-dai/waxml/trunk/AtlasXmlBeans2/src/main/xsd/WaxMlSchema/SampleDocuments/StructureTermsResponse_min.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio Developer Edition (Education) 8.1.2.2399 (http://www.liquid-technologies.com) -->
<wax:structureTermsResponse xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wax="http://www.incf.org/waxML" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.incf.org/waxML C:\dev_incf_google\atlas-aba\trunk\src\main\resources\WaxMlSchema\WaxML_Base.xsd">
    <wax:queryInfo>
        <wax:timeCreated>1998-09-19T09:55:47.49</wax:timeCreated>
        <wax:queryUrl>http://www.liquid-technologies.com</wax:queryUrl>
        <wax:criteria>
            <wax:input name="POI">
                <gml:Point srsName="INCF:ABAvoxel">
                    <gml:pos>x,y,z</gml:pos>
                </gml:Point>
            </wax:input>
            <wax:input name="StructureVocabulary">ABAvoxel</wax:input>
            <wax:input name="StructureFilter">structureset:Fine</wax:input>
        </wax:criteria>
    </wax:queryInfo>
    <wax:structureTerms>
        <wax:StructureTerm>
            <wax:structureCode gml:id="1369" codeSpace="ABAvoxel">HIP</wax:structureCode>
            <wax:description>Hippocampus, segmented </wax:description>
        </wax:StructureTerm>
    </wax:structureTerms>
</wax:structureTermsResponse>
